module.exports = {
  exclude: ['./test/**/*', '**/*.types.ts'],
  excludeExternals: true,
  excludeNotExported: true,
  excludePrivate: true,
  excludeProtected: true,
  ignoreCompilerErrors: true,
  includes: './src/**',
  includeVersion: true,
  mode: 'file',
  module: 'es2015',
  out: './docs/',
  target: 'ES6',
  tsconfig: './tsconfig.json',
};
